const API_BASE = (window.K3_API_BASE || 'http://localhost:5000/api/tindakan').replace(/\/$/, '');
const body = document.getElementById('action-table-body');
const form = document.getElementById('action-form');
const modal = document.getElementById('action-modal');
const search = document.getElementById('action-search');
const errorBox = document.getElementById('action-form-error');
const state = { rows: [], page: 1, size: 10, editId: null };
const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function token(){return localStorage.getItem('token') || localStorage.getItem('authToken') || '';}
async function request(path='', options={}){
  const headers = {'Content-Type':'application/json', ...(options.headers||{})};
  if(token()) headers.Authorization = `Bearer ${token()}`;
  const r = await fetch(`${API_BASE}${path}`, {...options, headers});
  const data = await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(data.message || `Request gagal (${r.status})`);
  return data;
}
function statusClass(v){const s=String(v||'').toLowerCase();return s.includes('closed')||s.includes('selesai')?'done':s.includes('progress')||s.includes('proses')?'progress':'open';}
function priorityClass(v){return String(v||'').toLowerCase();}
function late(row){if(statusClass(row.status)==='done')return false;const d=new Date(row.due_date);return !Number.isNaN(d.getTime()) && d.getTime()<new Date().setHours(0,0,0,0);}
function date(v){if(!v)return '-';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString('id-ID');}
function val(r,...keys){for(const k of keys)if(r[k]!==undefined&&r[k]!==null&&r[k]!=='')return r[k];return '-';}
function filtered(){const q=search.value.trim().toLowerCase(), st=$('filter-status').value, pr=$('filter-priority').value, so=$('filter-source').value, from=$('filter-from').value, to=$('filter-to').value;return state.rows.filter(r=>{const text=[r.action_code,r.source,r.description,r.assignee].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(st&&String(r.status)!==st)return false;if(pr&&String(r.priority)!==pr)return false;if(so&&String(r.source)!==so)return false;if(from&&String(r.due_date).slice(0,10)<from)return false;if(to&&String(r.due_date).slice(0,10)>to)return false;return true;});}
function renderTable(){const rows=filtered(), pages=Math.max(1,Math.ceil(rows.length/state.size));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.size, pageRows=rows.slice(start,start+state.size);$('result-info').textContent=`Menampilkan ${rows.length?start+1:0} - ${Math.min(start+state.size,rows.length)} dari ${rows.length} data`;if(!pageRows.length){body.innerHTML='<tr><td colspan="9">Tidak ada data yang sesuai filter.</td></tr>';}else body.innerHTML=pageRows.map((r,i)=>{const l=late(r);return `<tr><td>${start+i+1}</td><td><b>${esc(val(r,'action_code','code','id'))}</b></td><td>${esc(val(r,'source','origin'))}</td><td>${esc(val(r,'description','problem'))}</td><td><span class="priority ${priorityClass(r.priority)}">${esc(val(r,'priority'))}</span></td><td>${esc(val(r,'assignee','responsible_person','owner'))}</td><td>${date(r.due_date)}${l?'<br><b class="late-text">(Terlambat)</b>':''}</td><td><span class="status ${statusClass(r.status)}">${esc(val(r,'status'))}</span></td><td><div class="action-buttons"><button class="edit" data-edit="${r.id}"><i class="fa-solid fa-pen"></i></button><button class="status-btn" data-toggle="${r.id}" title="Ubah status"><i class="fa-solid fa-arrows-rotate"></i></button><button class="delete" data-delete="${r.id}"><i class="fa-solid fa-trash"></i></button></div></td></tr>`;}).join('');$('prev-page').disabled=state.page<=1;$('next-page').disabled=state.page>=pages;$('page-buttons').innerHTML=Array.from({length:Math.min(pages,5)},(_,i)=>`<button type="button" class="${i+1===state.page?'active-page':''}" data-page="${i+1}">${i+1}</button>`).join('');}
function renderStats(s){$('action-stat-total').textContent=s.total;$('action-stat-open').textContent=s.open;$('action-stat-progress').textContent=s.progress;$('action-stat-done').textContent=s.done;$('action-stat-late').textContent=s.late;$('sidebar-action-count').textContent=s.open+s.progress;}
function renderSide(s){$('donut-total').innerHTML=`${s.total}<small>Total</small>`;const t=s.total||1;const p=v=>((v/t)*100).toFixed(1);$('status-donut').style.background=`conic-gradient(#ef4444 0 ${p(s.open)}%,#f59e0b ${p(s.open)}% ${p(s.open+s.progress)}%,#059669 ${p(s.open+s.progress)}% ${p(s.open+s.progress+s.done)}%,#8b5cf6 ${p(s.open+s.progress+s.done)}% 100%)`;$('status-summary').innerHTML=`<p><b class="red-dot"></b> Terbuka <strong>${s.open} (${p(s.open)}%)</strong></p><p><b class="yellow-dot"></b> Dalam Proses <strong>${s.progress} (${p(s.progress)}%)</strong></p><p><b class="green-dot"></b> Selesai <strong>${s.done} (${p(s.done)}%)</strong></p><p><b class="purple-dot"></b> Terlambat <strong>${s.late} (${p(s.late)}%)</strong></p>`;const max=Math.max(s.priority.high,s.priority.medium,s.priority.low,1);$('priority-summary').innerHTML=[['High',s.priority.high,'#ef4444'],['Medium',s.priority.medium,'#f59e0b'],['Low',s.priority.low,'#059669']].map(x=>`<div class="bar-row"><span>${x[0]}</span><div><b style="width:${(x[1]/max)*100}%;background:${x[2]}"></b></div><strong>${x[1]}</strong></div>`).join('');$('source-summary').innerHTML=Object.entries(s.sources).map(([k,v])=>`<div><i class="fa-solid ${k==='Observasi'?'fa-clipboard-check':k==='Insiden'?'fa-triangle-exclamation':k==='Audit'?'fa-clipboard-list':'fa-magnifying-glass'} blue"></i><b>${v}</b><span>${esc(k)}</span></div>`).join('');}
function renderLate(rows){$('late-actions').innerHTML=rows.length?rows.slice(0,3).map(r=>`<div class="late-row"><i class="fa-regular fa-clock"></i><p><b>${esc(val(r,'action_code','code','id'))}</b><br><small>${esc(val(r,'description'))}</small></p><span>${date(r.due_date)}</span><a href="#" data-edit="${r.id}">Lihat</a></div>`).join(''):'<div class="empty">Tidak ada tindakan terlambat.</div>';}
async function load(){body.innerHTML='<tr><td colspan="9">Memuat data tindakan...</td></tr>';$('api-status').textContent='Menghubungkan...';$('api-status').className='api-status';try{const [list,summary]=await Promise.all([request(''),request('/summary')]);state.rows=list.data||[];renderTable();renderStats(summary.data.stats);renderSide(summary.data);renderLate(summary.data.late_actions||[]);populateSources(state.rows);$('api-status').textContent='Database terhubung';$('api-status').className='api-status ok';}catch(e){body.innerHTML=`<tr><td colspan="9">${esc(e.message)}</td></tr>`;$('api-status').textContent='Database tidak terhubung';$('api-status').className='api-status error';}}
function populateSources(rows){const current=$('filter-source').value;const sources=[...new Set(rows.map(r=>r.source).filter(Boolean))].sort();$('filter-source').innerHTML='<option value="">Semua Sumber</option>'+sources.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('filter-source').value=current;}
function openModal(row=null){state.editId=row?.id||null;form.reset();form.elements.id.value=row?.id||'';form.elements.source.value=row?.source||'';form.elements.description.value=row?.description||'';form.elements.priority.value=row?.priority||'Medium';form.elements.assignee.value=row?.assignee||'';form.elements.due_date.value=String(row?.due_date||'').slice(0,10);form.elements.status.value=row?.status||'Open';$('action-modal-title').textContent=row?'Edit Tindakan Korektif':'Buat Tindakan Korektif';errorBox.textContent='';modal.hidden=false;form.elements.source.focus();}
function closeModal(){modal.hidden=true;state.editId=null;errorBox.textContent='';}
async function save(e){e.preventDefault();errorBox.textContent='';const btn=form.querySelector('button[type=submit]');btn.disabled=true;try{const data=Object.fromEntries(new FormData(form).entries());delete data.id;await request(state.editId?`/${state.editId}`:'',{method:state.editId?'PUT':'POST',body:JSON.stringify(data)});closeModal();await load();}catch(err){errorBox.textContent=err.message;}finally{btn.disabled=false;}}
async function del(id){if(!confirm('Hapus tindakan korektif ini?'))return;try{await request(`/${id}`,{method:'DELETE'});await load();}catch(e){alert(e.message);}}
async function toggle(id){const row=state.rows.find(x=>Number(x.id)===Number(id));if(!row)return;const next=String(row.status)==='Open'?'In Progress':String(row.status)==='In Progress'?'Closed':'Open';if(!confirm(`Ubah status menjadi ${next}?`))return;try{await request(`/${id}`,{method:'PUT',body:JSON.stringify({...row,status:next})});await load();}catch(e){alert(e.message);}}
body.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'), delBtn=e.target.closest('[data-delete]'), tog=e.target.closest('[data-toggle]');if(edit){e.preventDefault();const row=state.rows.find(x=>Number(x.id)===Number(edit.dataset.edit));if(row)openModal(row);}if(delBtn)del(Number(delBtn.dataset.delete));if(tog)toggle(Number(tog.dataset.toggle));});
$('add-action-button').onclick=()=>openModal();$('close-action-modal').onclick=closeModal;$('cancel-action-modal').onclick=closeModal;form.onsubmit=save;search.oninput=()=>{state.page=1;renderTable()};['filter-status','filter-priority','filter-source','filter-from','filter-to'].forEach(id=>$(id).onchange=()=>{state.page=1;renderTable()});$('reset-filter').onclick=()=>{search.value='';$('filter-status').value='';$('filter-priority').value='';$('filter-source').value='';$('filter-from').value='';$('filter-to').value='';state.page=1;renderTable()};$('prev-page').onclick=()=>{if(state.page>1){state.page--;renderTable()}};$('next-page').onclick=()=>{state.page++;renderTable()};$('page-buttons').onclick=e=>{const b=e.target.closest('[data-page]');if(b){state.page=Number(b.dataset.page);renderTable()}};$('view-late').onclick=e=>{e.preventDefault();state.rows=state.rows.slice().sort((a,b)=>new Date(a.due_date)-new Date(b.due_date));search.value='';$('filter-status').value='';state.page=1;renderTable()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('live-date').textContent=new Date().toLocaleDateString('id-ID',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});load();
